<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>CONTACT</title>';
echo '<link rel="stylesheet" type="text/css" href="css/stylec.css">';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="main">';
echo '<ul>';
echo '<li><a href="index.php">Home</a></li>';
echo '<li><a href="product.php">Product</a></li>';
echo '<li><a href="gallery.php">Gallery</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '<li><a href="about.php">About us</a></li>';
echo '<li><a href="login.php">Login</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="container">';
echo '<h1>Contact us</h1>';
echo '<div class="contact-box">';
echo '<div class="contact-left">';
echo '<h3>Send your request</h3>';
echo '<form>';
echo '<div class="input-row">';
echo '<div class="input-group">';
echo '<label>Name</label>';
echo '<input type="text" placeholder="..." >';
echo '</div>';
echo '<div class="input-group">';
echo '<label>Phone</label>';
echo '<input type="text" placeholder="..." >';
echo '</div>';
echo '<div class="input-group">';
echo '<label>Email</label>';
echo '<input type="text" placeholder="..." >';
echo '</div>';
echo '<div class="input-group">';
echo '<label>Subject</label>';
echo '<input type="text" placeholder="..." >';
echo '</div>';
echo '</div>';
echo '<label>Message</label>';
echo '<textarea rows="5" placeholder="..."></textarea>';
echo '<button type="submit">Send</button>';
echo '</form>';
echo '';
echo '</div>';
echo '<div class="contact-right">';
echo '<h3>Reach us</h3>';
echo '<table>';
echo '<tr>';
echo '<td>Name:</td>';
echo '<td>Georgi Parushev</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Phone:</td>';
echo '<td>088 888 8888</td>';
echo '</tr>';
echo '<tr>';
echo '<td>Email:</td>';
echo '<td>BSW@mail.com</td>';
echo '</tr>';
echo '</table>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '';
echo '</body>';
echo '</html>';
?>