<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>GALLERY</title>';
echo '<link rel="stylesheet" type="text/css" href="css/styleg.css">';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="main">';
echo '<ul>';
echo '<li><a href="index.php">Home</a></li>';
echo '<li><a href="product.php">Product</a></li>';
echo '<li><a href="gallery.php">Gallery</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '<li><a href="about.php">About us</a></li>';
echo '<li><a href="login.php">Login</a></li>';
echo '</ul>';
echo '</div>';
echo '<h1>Gallery</h1>';
echo '<div class="container">';
echo '<div class="gallery">';
echo '<img src="img/watch1.jpg">';
echo '</div>';
echo '<div class="gallery">';
echo '<img src="img/watch2.jpg">';
echo '</div>';
echo '<div class="gallery">';
echo '<img src="img/watch3.jpg">';
echo '</div>';
echo '<div class="gallery">';
echo '<img src="img/watch4.jpg">';
echo '</div>';
echo '<div class="gallery">';
echo '<img src="img/watch5.jpg">';
echo '</div>';
echo '<div class="gallery">';
echo '<img src="img/watch6.jpg">';
echo '</div>';
echo '</div>';
echo '</header>';
echo '';
echo '</body>';
echo '</html>';
?>