<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>LOGIN</title>';
echo '<link rel="stylesheet" type="text/css" href="css/stylel.css">';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="main">';
echo '<ul>';
echo '<li><a href="index.php">Home</a></li>';
echo '<li><a href="product.php">Product</a></li>';
echo '<li><a href="gallery.php">Gallery</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '<li><a href="about.php">About us</a></li>';
echo '<li><a href="login.php">Login</a></li>';
echo '</ul>';
echo '</div>';
echo '<h1>Login</h1>';
echo '<div class="container">';
echo '<div class="register-box">';
echo '<div class="login-left">';
echo '<h3>Login to your account</h3>';
echo '<form>';
echo '<div class="input-row">';
echo '<div class="input-group">';
echo '<label>Username</label>';
echo '<input type="text" placeholder="..." >';
echo '</div>';
echo '<div class="input-group">';
echo '<label>Password</label>';
echo '<input type="Password" placeholder="..." >';
echo '</div>';
echo '</div>';
echo '<button type="Login">Login</button>';
echo '</form>';
echo '';
echo '</div>';
echo '<div class="register-right">';
echo '<h3>Dont have an account ?</h3>';
echo '<button>Create one</button>';
echo '';
echo '</div>';
echo '</header>';
echo '';
echo '</body>';
echo '</html>';
?>