<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>PRODUCT</title>';
echo '<link rel="stylesheet" type="text/css" href="css/stylep.css">';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="main">';
echo '<ul>';
echo '<li><a href="index.php">Home</a></li>';
echo '<li><a href="product.php">Product</a></li>';
echo '<li><a href="gallery.php">Gallery</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '<li><a href="about.php">About us</a></li>';
echo '<li><a href="login.php">Login</a></li>';
echo '</ul>';
echo '</div>';
echo '<h1>Product</h1>';
echo '<div class="container1">';
echo '<p><b>-Features:</b>    BT call, bracelet local music playback, connectable to TWS/audio, etc.';
echo '</p>';
echo '<p><b>-charging method:</b>    Magnetic adsorption.</p>';
echo '<p><b>-message notification:</b>    Vibrating icon reminder and content display of QQ, WeChat, messaging, and other APP information.';
echo '</p>';
echo '<p><b>-Exercise step count:</b>    Exercise steps, exercise mileage records, caliber consumption, multiple exercise modes.</p>';
echo '<p><b>-Health monitoring:</b>    Sleep monitoring, sedentary reminder, drink reminder, all-weather heart rate detection, exercise record.';
echo '</p>';
echo '<p><b>-Standby use time:</b>    BLE connection use 7-10 days, dual Bluetooth state use time 3-5 days, continuous call or music playback 5 hours.</p>';
echo '<p><b>-Other functions:</b>    Mute alarm clock, remote camera, music control, weather, etc.';
echo '</p>';
echo '<p><b>-Firmware language:</b>    Bulgarian, Chinese, English, French, German, Italian, Spanish, Portuguese, Russian, Japanese, Dutch, Thai.';
echo '</p>';
echo '';
echo '</div>';
echo '<div class="container2">';
echo '<div class="image">';
echo '<img src="img/watch1.jpg">';
echo '</div>';
echo '</div>';
echo '<h2>100 BGN</h2>';
echo '<button>Buy now</button>';
echo '</header>';
echo '';
echo '</body>';
echo '</html>';
?>